### ISSUE TITLE
Map not showing on browser

### ISSUE THREAD

**Issue by DNCorona** [ebrelsford/projestions#12]
Hi, I've been using https://projest.io/ns/ to teach my students about coordinates systems in GIS class without problem, but starting from this semester the browser didn't show the OSM map anymore

![Captura de pantalla 2024-04-07 144624](https://github.com/ebrelsford/projestions/assets/166335600/797209a0-0237-4c8c-b36f-90f9a4ae2544)

**Comment by ebrelsford** [comment]
Thanks for letting me know @DNCorona! I know what's going on here and shuld be able to fix it soon.

**Comment by ebrelsford** [comment]
@DNCorona you should be set now, thanks for letting me know.
