### ISSUE TITLE
sort by hausdorff distance of extents (sort by extent similarity)

### ISSUE THREAD

**Issue by stevefaeembra** [ebrelsford/projestions#7]
Kudos for this! I'd tried implementing something similar myself, but never got round to productising it.

You might like to look at sorting ascending by **[ST_HausdorffDistance(selected_geometry, crs_extent_geometry)](http://postgis.net/docs/ST_HausdorffDistance.html)** as a possible option in your query. 

The closer the two polygons are in extent and size, the lower the value (so small values are closer matches). I found this gave quite intuitive results. 

I suspect in most cases they'll be very similar to your current results. Maybe worth trying and see what you think?

**Comment by ebrelsford** [comment]
Thanks, that's a good idea! I will give it a look.

**Comment by ebrelsford** [comment]
I'm testing this out and it seems to fix ebrelsford/qgis-projestions#3. Will likely add a parameter to specify the ordering, currently it just picks the smallest area-of-use.

**Comment by ebrelsford** [comment]
Okay I've added this as an option in the API and you can play around with it on the [demo](http://projest.io/ns/). Thanks again for the suggestion!
