### ISSUE TITLE
Suggestions are incomplete - Example Cambodia

### ISSUE THREAD

**Issue by wildintellect** [ebrelsford/projestions#9]
If you put a marker in Cambodia you only get a Pacific Ocean projection. If you draw a box or polygon you get plenty of valid suggestions but not DGN 95 or  WGS 84 / UTM Z48N http://epsg.io/32648
Not quite sure why, maybe they are missing from the database? Both are in QGIS and on EPSG.io which use the same source.

**Comment by ebrelsford** [comment]
Thanks for getting in touch. How exactly are you using projestions? Through the [web interface](http://projest.io/ns/)?

If so, I do get pretty reasonable suggestions (including UTM 48N) for a marker in Cambodia:

![selection_022](https://cloud.githubusercontent.com/assets/375002/24718419/ed6ba9b0-1a03-11e7-8916-168370c13c4d.png)

Let me know if you're using it some other way or if I'm missing something, really happy to improve the suggestions however we can!

**Comment by wildintellect** [comment]
Odd, I tried both QGIS and the Web interface. Maybe I missed it when scrolling, I see it in the web now. QGIS still doesn't show WGS 84 / UTM Z48N http://epsg.io/32648 . I can see why DGN 95  UTM Z48N doesn't show, it's bounding box just covers Indonesia http://epsg.io/23868

**Comment by ebrelsford** [comment]
I see UTM Z48N in QGIS:

![selection_001](https://cloud.githubusercontent.com/assets/375002/25151877/2ed65a3e-2455-11e7-9de9-b2133df9370f.png)

I am zoomed in pretty far when I do so, maybe that has something to do with it? Are you using the latest version (v0.1.2)? Any other info you can provide about how you're using it would be appreciated!

**Comment by wildintellect** [comment]
So I was using it by loading a shape of Cambodia (attached), then querying based on the layer. If I use a layer of points that are well within the country it works. Very odd.
[cambodia.geojson.zip](https://github.com/ebrelsford/projestions/files/945743/cambodia.geojson.zip)

**Comment by ebrelsford** [comment]
Okay thanks for the data, that helps. I'm going to investigate soon.

**Comment by ebrelsford** [comment]
So I've been looking into this, and I think it has to do with the way I'm currently finding matches from QGIS. I'm using the extent of the active layer, and that **bounding box** is a pretty good match for Laos and other nearby areas.

I'm considering a few additional options for the QGIS plugin:
 * Use the centroid of the extent instead, look for projections with similar centroids
 * Select a feature or features from your layer and send them to the API

**Comment by ebrelsford** [comment]
@wildintellect I think I've made a lot of progress here, and I'm interested in hearing your feedback. Try out `v0.2.0` of the plugin in QGIS when you get a chance? There's a new option to use the geometry of the active layer rather than the extent, and the matches are prioritized in a much more logical way now. Let me know and I can close this if you think it's better.

![projestions_028](https://user-images.githubusercontent.com/375002/28279490-9e8eb18e-6aee-11e7-8554-b77fd929cb9e.png)

**Comment by wildintellect** [comment]
Yes, I tried this out and confirm the results. The expected projection is in the top 3 results now, and differs greatly from the canvas and project extent results.

**Comment by ebrelsford** [comment]
Great thanks for confirming!
